server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    server:
      eviction-interval-timer-in-ms: 60000
spring:
  application:
    name: discovery-server

