spring:
      application:
              name: cloud-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
cloud:
  config:
    enabled: true
    import-check:
      enabled: true
      gateway:
            routes:
                  - id: auth-service
                    uri: http://localhost:8081
                    predicates:
                          - Path=/api/auth/**
                    filters:
                          - AuthenticationFilter
                          - AddResponseHeader=X-Content-Type-Options:nosniff;

                  - id: comesse-service
                    uri: http://localhost:8082
                    predicates:
                          - Path=/api/commesse/**
                    filters:
                          - AuthenticationFilter
                          - AddResponseHeader=X-Content-Type-Options:nosniff;

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration:
    milliseconds:
              long: ${JWT_EXPIRATION_MILLISECONDS}


